import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# --- Set polished style ---
sns.set_style("whitegrid")
plt.rcParams['axes.labelsize'] = 12
plt.rcParams['axes.titlesize'] = 16

# --- Load CSV files generated by Pig ---
top_products = pd.read_csv("top_products.csv", header=None, names=["product_name", "total_revenue", "total_quantity"])
customer_revenue = pd.read_csv("top_customers.csv", header=None, names=["customer_id", "total_spent"])

# --- Top 5 Products by Revenue as Pie Chart ---
top5_products = top_products.sort_values("total_revenue", ascending=False).head(5)
plt.figure(figsize=(8,8))
colors = sns.color_palette("pastel")[0:5]  # crystal pastel colors
plt.pie(
    top5_products["total_revenue"],
    labels=top5_products["product_name"],
    autopct="%1.1f%%",
    colors=colors,
    startangle=140,
    wedgeprops={"edgecolor": "k", "linewidth": 1}
)
plt.title("Top 5 Products by Revenue", weight='bold')
plt.tight_layout()
plt.savefig("top_products_pie.png")
plt.close()

# --- Top 5 Customers by Spending as Bar Chart ---
plt.figure(figsize=(10,6))
top5_customers = customer_revenue.sort_values("total_spent", ascending=False).head(5)
sns.barplot(
    x="total_spent",
    y="customer_id",
    data=top5_customers,
    palette="viridis_r"
)
plt.title("Top 5 Customers by Spending", weight='bold')
plt.xlabel("Total Spent ($)")
plt.ylabel("Customer ID")
for index, value in enumerate(top5_customers["total_spent"]):
    plt.text(value + 20, index, f"${value:,.2f}", va='center')
plt.tight_layout()
plt.savefig("top_customers_chart.png")
plt.close()

print("Charts generated successfully: top_products_pie.png, top_customers_chart.png")
